<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Office;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepartmentAndOfficeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks during truncation/seeding
        // DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        // Office::truncate();
        // Department::truncate();
        // DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $data = [
            'Bansalan East' => [
                ['code' => '128810', 'name' => 'Balagonon Elementary School'],
                ['code' => '502868', 'name' => 'Balutakay Integrated School'],
                ['code' => '128812', 'name' => 'Bansalan Central Elementary School'],
                ['code' => '128813', 'name' => 'Bonifacio Elementary School'],
                ['code' => '128814', 'name' => 'Buenavista Elementary School'],
                ['code' => '128815', 'name' => 'Mabuhay Elementary School'],
                ['code' => '128816', 'name' => 'Mabunga Elementary School'],
                ['code' => '128817', 'name' => 'Managa Elementary School'],
                ['code' => '128818', 'name' => 'New Clarin Elementary School'],
                ['code' => '128819', 'name' => 'Rizal Elementary School'],
                ['code' => '128820', 'name' => 'Santo Niño Elementary School'],
                ['code' => '128821', 'name' => 'Union Elementary School'],
                ['code' => '128822', 'name' => 'Villa Vicente Elementary School'],
                ['code' => '304203', 'name' => 'Bansalan National High School'],
                ['code' => '304221', 'name' => 'Mabunga National High School'],
                ['code' => '304222', 'name' => 'Marber National High School'],
                ['code' => '305886', 'name' => 'New Clarin National High School'],
            ],
            'Bansalan West' => [
                ['code' => '128823', 'name' => 'Alegre Elementary School'],
                ['code' => '128824', 'name' => 'Altavista Elementary School'],
                ['code' => '128825', 'name' => 'Anonang Elementary School'],
                ['code' => '128826', 'name' => 'Bitaug Elementary School'],
                ['code' => '128827', 'name' => 'Dolo Elementary School'],
                ['code' => '128828', 'name' => 'Kinuskusan Elementary School'],
                ['code' => '128829', 'name' => 'Marber Elementary School'],
                ['code' => '128830', 'name' => 'New Visayas Elementary School'],
                ['code' => '128831', 'name' => 'Poblacion Dos Elementary School'],
                ['code' => '128832', 'name' => 'Salendab Elementary School'],
                ['code' => '128833', 'name' => 'Sibawan Elementary School'],
                ['code' => '128834', 'name' => 'Tinasagan Elementary School'],
                ['code' => '128835', 'name' => 'Tubod Elementary School'],
                ['code' => '128836', 'name' => 'Vicente Tatel Elementary School'],
                ['code' => '304202', 'name' => 'Anonang National High School'],
                ['code' => '304218', 'name' => 'Kinuskusan National High School'],
                ['code' => '304239', 'name' => 'Tubod National High School'],
            ],
            'Hagonoy I' => [
                ['code' => '128837', 'name' => 'Aplaya Elementary School'],
                ['code' => '128838', 'name' => 'Balutakay Elementary School'],
                ['code' => '128839', 'name' => 'Clario Caluya Elementary School'],
                ['code' => '128840', 'name' => 'Guihing Central Elementary School'],
                ['code' => '128841', 'name' => 'Hagonoy Central Elementary School'],
                ['code' => '128842', 'name' => 'Lologan Elementary School'],
                ['code' => '128843', 'name' => 'Malabang Elementary School'],
                ['code' => '128844', 'name' => 'Poblacion Central Elementary School'],
                ['code' => '128845', 'name' => 'Sacub Elementary School'],
                ['code' => '128846', 'name' => 'San Jose Elementary School'],
                ['code' => '304212', 'name' => 'Guihing National High School'],
                ['code' => '304213', 'name' => 'Hagonoy National High School'],
                ['code' => '304230', 'name' => 'Sacub National High School'],
            ],
            'Hagonoy II' => [
                ['code' => '128847', 'name' => 'Kibuaya Elementary School'],
                ['code' => '128848', 'name' => 'La Union Elementary School'],
                ['code' => '128849', 'name' => 'Lanuro Elementary School'],
                ['code' => '128850', 'name' => 'Mahiyahin Elementary School'],
                ['code' => '128851', 'name' => 'Malalag Cogon Elementary School'],
                ['code' => '128852', 'name' => 'Paligue Elementary School'],
                ['code' => '128853', 'name' => 'Perez Integrated School'],
                ['code' => '128854', 'name' => 'San Guillermo Elementary School'],
                ['code' => '128855', 'name' => 'Sinayawan Elementary School'],
                ['code' => '501726', 'name' => 'Tungatung Elementary School'],
                ['code' => '304207', 'name' => 'Carmelo de los Cientos Sr. National High School'],
            ],
            'Kiblawan North' => [
                ['code' => '128856', 'name' => 'Bagumbayan Elementary School'],
                ['code' => '128857', 'name' => 'Balasiao Elementary School'],
                ['code' => '128858', 'name' => 'Bunot Elementary School'],
                ['code' => '128859', 'name' => 'Dapok Elementary School'],
                ['code' => '128860', 'name' => 'Iba Elementary School'],
                ['code' => '128861', 'name' => 'Kiblawan Central Elementary School'],
                ['code' => '128862', 'name' => 'Kimlawis Elementary School'],
                ['code' => '128863', 'name' => 'Kisulao Elementary School'],
                ['code' => '128864', 'name' => 'Maraga-a Elementary School'],
                ['code' => '128865', 'name' => 'Pocaleel Elementary School'],
                ['code' => '128866', 'name' => 'San Fernando Elementary School'],
                ['code' => '128867', 'name' => 'Tacub Elementary School'],
                ['code' => '304204', 'name' => 'Balasiao National High School'],
                ['code' => '304219', 'name' => 'Kiblawan National High School'],
                ['code' => '305885', 'name' => 'Kimlawis National High School'],
            ],
            'Kiblawan South' => [
                ['code' => '128868', 'name' => 'Abong-Abong Elementary School'],
                ['code' => '128869', 'name' => 'Bagong Gutierrez Elementary School'],
                ['code' => '128870', 'name' => 'Bagong Negro Elementary School'],
                ['code' => '128871', 'name' => 'Bongkikil Elementary School'],
                ['code' => '128872', 'name' => 'Bulol-Salo Elementary School'],
                ['code me' => '128873', 'name' => 'Cogon-Bacaca Elementary School'],
                ['code' => '128874', 'name' => 'Lawa-an Elementary School'],
                ['code' => '128875', 'name' => 'Manual Elementary School'],
                ['code' => '128876', 'name' => 'Molopolo Elementary School'],
                ['code' => '128877', 'name' => 'Pasig Elementary School'],
                ['code' => '128878', 'name' => 'San Pedro Elementary School'],
                ['code' => '128879', 'name' => 'Waterfall Elementary School'],
                ['code' => '304209', 'name' => 'Iba National High School'],
                ['code' => '304226', 'name' => 'Pasig National High School'],
                ['code' => '304231', 'name' => 'San Pedro National High School'],
            ],
            'Magsaysay North' => [
                ['code' => '128880', 'name' => 'Bacungan Elementary School'],
                ['code' => '128881', 'name' => 'Balagatan Elementary School'],
                ['code' => '128882', 'name' => 'Barayong Central Elementary School'],
                ['code' => '128883', 'name' => 'Bongon Elementary School'],
                ['code' => '128884', 'name' => 'Dalawinon Elementary School'],
                ['code' => '128885', 'name' => 'Kasuga Elementary School'],
                ['code' => '128886', 'name' => 'Magsaysay Central Elementary School'],
                ['code' => '128887', 'name' => 'Malawanit Elementary School'],
                ['code' => '128888', 'name' => 'Maybo Elementary School'],
                ['code' => '128889', 'name' => 'San Antonio Elementary School'],
                ['code' => '128890', 'name' => 'San Isidro Elementary School'],
                ['code' => '128891', 'name' => 'Tacul Elementary School'],
                ['code' => '128892', 'name' => 'Tuguis Elementary School'],
                ['code' => '304205', 'name' => 'Barayong National High School'],
                ['code' => '304236', 'name' => 'Tacul Agricultural High School'],
            ],
            'Magsaysay South' => [
                ['code' => '128893', 'name' => 'Balawag Elementary School'],
                ['code' => '128894', 'name' => 'Canocotan Elementary School'],
                ['code' => '128895', 'name' => 'Guitas Elementary School'],
                ['code' => '128896', 'name' => 'Kalao Elementary School'],
                ['code' => '128897', 'name' => 'Katipunan Elementary School'],
                ['code' => '128898', 'name' => 'Lower Bala Elementary School'],
                ['code' => '128899', 'name' => 'Mabini Elementary School'],
                ['code' => '128900', 'name' => 'New 희망 Elementary School'],
                ['code' => '128901', 'name' => 'Poblacion Integrated School'],
                ['code' => '128902', 'name' => 'San Jose Elementary School'],
                ['code' => '128903', 'name' => 'Tagalio Elementary School'],
                ['code' => '128904', 'name' => 'Upper Bala Elementary School'],
                ['code' => '304210', 'name' => 'Inocencio V. Vivares NHS'],
                ['code' => '304216', 'name' => 'Katipunan National High School'],
            ],
            'Malalag' => [
                ['code' => '128905', 'name' => 'Bagumbayan Elementary School'],
                ['code' => '128906', 'name' => 'Baybay Elementary School'],
                ['code' => '128907', 'name' => 'Bolton Elementary School'],
                ['code' => '128908', 'name' => 'Bulacan Elementary School'],
                ['code' => '128909', 'name' => 'Caputian Elementary School'],
                ['code' => '128910', 'name' => 'Ibo Elementary School'],
                ['code' => '128911', 'name' => 'Kiblawan Elementary School'],
                ['code' => '128912', 'name' => 'Laplawan Elementary School'],
                ['code' => '128913', 'name' => 'Mabini Elementary School'],
                ['code' => '128914', 'name' => 'Malalag Central Elementary School'],
                ['code' => '128915', 'name' => 'New Laguna Elementary School'],
                ['code' => '128916', 'name' => 'Pagsabangan Elementary School'],
                ['code' => '128917', 'name' => 'Rizal Elementary School'],
                ['code' => '128918', 'name' => 'San Isidro Elementary School'],
                ['code' => '128919', 'name' => 'Tagansule Elementary School'],
                ['code' => '304206', 'name' => 'Bolton National High School'],
                ['code' => '304220', 'name' => 'Malalag National High School'],
                ['code' => '304237', 'name' => 'Tagansule National High School'],
            ],
            'Matanao I' => [
                ['code' => '128920', 'name' => 'Bangkal Elementary School'],
                ['code' => '128921', 'name' => 'Buas Integrated School'],
                ['code' => '128922', 'name' => 'Cabligan Elementary School'],
                ['code' => '128923', 'name' => 'Kauswagan Elementary School'],
                ['code' => '128924', 'name' => 'Kiblawan Central Elementary School'],
                ['code' => '128925', 'name' => 'Manga Elementary School'],
                ['code' => '128926', 'name' => 'Matanao Central Elementary School'],
                ['code' => '128927', 'name' => 'Sinait Elementary School'],
                ['code' => '128928', 'name' => 'Tamlangon Elementary School'],
                ['code' => '128929', 'name' => 'Towak Elementary School'],
                ['code' => '304201', 'name' => 'Bangkal National High School'],
                ['code' => '304223', 'name' => 'Matanao National High School'],
            ],
            'Matanao II' => [
                ['code' => '128930', 'name' => 'Asbang Elementary School'],
                ['code' => '128931', 'name' => 'Bongalonan Elementary School'],
                ['code' => '128932', 'name' => 'Colonsabak Elementary School'],
                ['code' => '128933', 'name' => 'Donganpekong Elementary School'],
                ['code' => '128934', 'name' => 'Kabasalan Elementary School'],
                ['code' => '128935', 'name' => 'La Suerte Elementary School'],
                ['code' => '128936', 'name' => 'Langa-an Elementary School'],
                ['code' => '128937', 'name' => 'New Lower Integrated School'],
                ['code' => '128938', 'name' => 'Saboy Elementary School'],
                ['code' => '128939', 'name' => 'San Jose Elementary School'],
                ['code' => '128940', 'name' => 'San Vicente Elementary School'],
                ['code' => '128941', 'name' => 'Tibiz Integrated School'],
                ['code' => '304208', 'name' => 'Donganpekong National High School'],
            ],
            'Padada' => [
                ['code' => '128942', 'name' => 'Almendras Elementary School'],
                ['code' => '128943', 'name' => 'Don Mariano Marcos Elementary School'],
                ['code' => '128944', 'name' => 'Lower Limonso Elementary School'],
                ['code' => '128945', 'name' => 'Padada Central Elementary School'],
                ['code' => '128946', 'name' => 'Palili Elementary School'],
                ['code' => '128947', 'name' => 'Punta Piape Elementary School'],
                ['code' => '128948', 'name' => 'San Isidro Elementary School'],
                ['code' => '128949', 'name' => 'Southern Paligue Elementary School'],
                ['code' => '128950', 'name' => 'Tulogan Elementary School'],
                ['code' => '128951', 'name' => 'Upper Limonso Elementary School'],
                ['code' => '304225', 'name' => 'Padada National High School'],
                ['code' => '304227', 'name' => 'Palili National High School'],
            ],
            'Sta. Cruz North' => [
                ['code' => '128952', 'name' => 'Bato Elementary School'],
                ['code' => '128953', 'name' => 'Inawayan Elementary School'],
                ['code' => '128954', 'name' => 'Langan Elementary School'],
                ['code' => '128955', 'name' => 'Melilia Elementary School'],
                ['code' => '128956', 'name' => 'Saliducon Elementary School'],
                ['code' => '128957', 'name' => 'Sibulan Elementary School'],
                ['code' => '128958', 'name' => 'Sta. Cruz Central Elementary School'],
                ['code' => '128959', 'name' => 'Tungalan Elementary School'],
                ['code' => '304214', 'name' => 'Inawayan National High School'],
                ['code' => '304232', 'name' => 'Sta. Cruz National High School'],
            ],
            'Sta. Cruz South' => [
                ['code' => '128960', 'name' => 'Astorga Elementary School'],
                ['code' => '128961', 'name' => 'Coronon Elementary School'],
                ['code' => '128962', 'name' => 'Darong Elementary School'],
                ['code' => '128963', 'name' => 'Lubogan Elementary School'],
                ['code' => '128964', 'name' => 'Matutungan Elementary School'],
                ['code' => '128965', 'name' => 'Sinawilan Elementary School'],
                ['code' => '128966', 'name' => 'Tagabuli Elementary School'],
                ['code' => '128967', 'name' => 'Tuban Elementary School'],
                ['code' => '304200', 'name' => 'Astorga National High School'],
                ['code' => '304233', 'name' => 'Tagabuli National High School'],
                ['code' => '304238', 'name' => 'Tuban National High School'],
            ],
            'Sulop' => [
                ['code' => '128968', 'name' => 'Balasinon Elementary School'],
                ['code' => '128969', 'name' => 'Buguis Elementary School'],
                ['code' => '128970', 'name' => 'Carnero Elementary School'],
                ['code' => '128971', 'name' => 'Harada Ondo Elementary School'],
                ['code' => '128972', 'name' => 'Katipunan Elementary School'],
                ['code' => '128973', 'name' => 'Kiblawan Elementary School'],
                ['code' => '128974', 'name' => 'Lapla Elementary School'],
                ['code' => '128975', 'name' => 'Litos Elementary School'],
                ['code' => '128976', 'name' => 'Luparan Elementary School'],
                ['code' => '128977', 'name' => 'Mckinley Elementary School'],
                ['code' => '128978', 'name' => 'New Cebu Elementary School'],
                ['code' => '128979', 'name' => 'Palili Elementary School'],
                ['code' => '128980', 'name' => 'Solongvale Elementary School'],
                ['code' => '128981', 'name' => 'Sulop Central Elementary School'],
                ['code' => '128982', 'name' => 'Talas Elementary School'],
                ['code' => '128983', 'name' => 'Tanwalang Elementary School'],
                ['code' => '304217', 'name' => 'Kiblawan National High School'],
                ['code' => '304224', 'name' => 'New Cebu National High School'],
                ['code' => '304234', 'name' => 'Sulop National High School'],
            ],
        ];

        foreach ($data as $departmentName => $offices) {
            $department = Department::firstOrCreate([
                'name' => $departmentName,
            ]);

            foreach ($offices as $office) {
                // Ensure array key fix if needed
                $code = $office['code'] ?? $office['code me'] ?? null;

                Office::create([
                    'department_id' => $department->id,
                    'code'          => $code,
                    'name'          => $office['name'],
                ]);
            }
        }
    }
}
